### ISSUE TITLE
epic: CML <> DVCLive

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1036]
Make it easy to publish CML reports from DVCLive.

```bash
cml send-comment --publish --watch=1min report.md &
python train.py --dvclive-report=report.md
```

- [x] #1026
  - `cml send-comment --publish`: auto-publish images embedded in markdown reports
  - `cml send-comment --watch` file-watcher
    + [x] file-based mutex lock
    + [ ] upstream: DVCLive support for file-based mutex lock
- [x] `cml publish` seed to help with [overwriting outdated files](https://github.com/iterative/cml/pull/1026#issuecomment-1139604345)
  - potentially related to #291
- [ ] upstream: DVCLive option to write `md` instead of `html` (https://github.com/iterative/dvc-render/issues/62)

### future follow-up

- [Happier userflow path](https://github.com/iterative/cml/pull/1026#discussion_r884750213)
  + user specifying DVCLive output formats to be `md` (or `md` and `html`)
  + [DVCLive auto-detecting CI env to decide what format to output](https://github.com/iterative/cml/pull/1026#discussion_r884636279)
  + CML auto-converting html2md (via e.g. `pandoc` or some JS lib)
- Studio renders reports (rather than just linking to GH)
  + detects dvclive reports (maybe with a special watermark) as a flag to poll for updates every minute

**Comment by 0x2b3bfa0** [comment]
Another possible interaction pattern:

```console
$ cml whatever python train.py
```

CML could trigger comment updates when the child process outputs a magic string to the standard output/error, and the child process could be aware of `cml whatever` because it can receive environment variables. 🤔

**Comment by 0x2b3bfa0** [comment]
> _What would be the main benefit of this alternative? The ability to share env vars with the `child` process?_

Yes, this would allow child processes to know that they're being watched. 🕵🏼

And perhaps communicate through standard output by printing some clunky magic strings. 🪓

**Comment by 0x2b3bfa0** [comment]
> _What happens when integrating with DVC `cml whatever dvc repro`?_

Presumably nothing unexpected. 🤔

**Comment by daavoo** [comment]
> > _What happens when integrating with DVC `cml whatever dvc repro`?_
> 
> Presumably nothing unexpected. 🤔

I was thinking that DVC will need to also share the env vars with the child process (i.e. train stage) so the direct benefit of the approach won't be directly aplicable to DVC use case without extra work

**Comment by daavoo** [comment]
> And perhaps communicate through standard output by printing some clunky magic strings.

Potential issue is that in DVCLive we try to not output to stdout durint training to prevent messing up with the ML Framework UI (i.e. some use funky progress vars)

**Comment by daavoo** [comment]
>  upstream: DVCLive support for file-based mutex lock

@0x2b3bfa0 @casperdcl could you give me some more context on this?

**Comment by casperdcl** [comment]
@daavoo soon (after #1073 <- #762), the idea is:

```bash
# simple
cml report watch --publish report.md &
python dvclive_script.py --output=report.md

# synchronised alternative
cml report watch --publish --trigger-file=/tmp/dvclive report.md &
python dvclive_script.py --output-report=report.md --output-trigger=/tmp/dvclive
```

where the "synchronised alternative" flow avoids potential contention. TL;DR pseudocode:

### DVCLive

```python
def next_step():
    ...
    if output_report:
        if output_trigger and output_trigger != output_report:
            if not output_trigger.exists():
                mkreport(output)
                output_trigger.touch()
        else:
            mkreport(output)
```

### CML

```python
while True:  # watcher thread
    if triggerFile and triggerFile != reportFile:
        if exists(triggerFile):
            upload(reportFile, ignore_missing=True)
            rm(triggerFile)
    else:
        upload(reportFile, ignore_missing=True, only_if_changed=True)
```
