### ISSUE TITLE
Move `REPO_TOKEN` to `CML_` environment variable namespace

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#763]
Use `CML_TOKEN` (or similar, e.g. `CML_CI_TOKEN` etc.) instead of `REPO_TOKEN` to

- avoid potential namespace clashes
- better reflect that it could be a project token, org token, bot token, encoded username & password, etc
- better reflect that it's mostly used to *launch* runners and also is used *by* runners

---

- from https://github.com/iterative/cml.dev/pull/122#issuecomment-941330742
- related #738, #741, #712

**Comment by 0x2b3bfa0** [comment]
Closed #764 because violets are red. Do you have any brilliant solution to this issue?

**Comment by casperdcl** [comment]
`CML_CI_TOKEN`?

**Comment by DavidGOrtega** [comment]
```CML_REPO_TOKEN```?

**Comment by 0x2b3bfa0** [comment]
* [x] `CML_TOKEN` by @casperdcl — concise and honored by `yargs` since [#1073](https://github.com/iterative/cml/pull/1073)
* [ ] `CML_FORGE_TOKEN` by @0x2b3bfa0[^1] — not honored by `yargs` and arguable as per [#1142](https://github.com/iterative/cml/pull/1142)
* [ ] ~`SCM_TOKEN` by @DavidGOrtega~ — conceptually flawed as per [#1073 (comment)](https://github.com/iterative/cml/pull/1073#discussion_r913275504)

[^1]: What @DavidGOrtega, @casperdcl and @dacbd really meant with attrocities like [`GIT_PROVIDER_TOKEN`](https://github.com/iterative/cml/issues/763#issuecomment-942475192), [`SCM_API_TOKEN`](https://github.com/iterative/cml/issues/763#issuecomment-942475192), 
[`CML_CI_TOKEN`](https://github.com/iterative/cml/issues/763#issuecomment-943653034) or [`CML_REPO_TOKEN`](https://github.com/iterative/cml/issues/763#issuecomment-944208619) in previous comments. 🐲

**Comment by 0x2b3bfa0** [comment]
I'd suggest just replacing `REPO_TOKEN` by `CML_TOKEN` in all our documentation and examples. 

🔔 @iterative/cml, please vote 👍🏼 👎🏼 on this comment.

**Comment by casperdcl** [comment]
currently still leaning towards `CML_CI_TOKEN`

**Comment by 0x2b3bfa0** [comment]
And how does `CI` describe the API that token is used for? 🤔

**Comment by dacbd** [comment]
because that token is needed by all the actions we preform in the CI system?

**Comment by 0x2b3bfa0** [comment]
That's also the case with all the other tokens. 🤔 They're usually not named after the system that uses them, but after the system that requires them for authentication.

E.g. if a token is used to authenticate with a cloud, it's a “cloud token” and not a “computer token” even if you use it from a computer. 😅

**Comment by dacbd** [comment]
:smile: it's more descriptive of what it is used for than `CML_TOKEN` is; cml does not have an API your need to interact with so why does it need a token to do anything??? `CI` is at least a fill-in for Github Actions/GitLab-CI/BB pipelines and you know the provider its making calls to. I understand your insistence to use the term forge, but it is still not commonplace.

If the issue is handling the chance for a collision just silently keep `CML_TOKEN` then namespace `REPO_TOKEN` that's what users know already and will be easier (mentally) to move to. If we want to have naming holy wars, we should have handled this with the command renaming.


I'd argue for the moment there's no problem to fix so let's not make it one...

**Comment by 0x2b3bfa0** [comment]
> _[`CML_CI_TOKEN`] is more descriptive of what it is used for than `CML_TOKEN` is_

Indeed, it has more words, although whether they help clarifying its purpose or not is arguable 😅 

> _`cml` does not have an API your need to interact with so why does it need a token to do anything?_

I fell on my own trap of https://github.com/iterative/cml/issues/763#issuecomment-1272156324; indeed, tokens should not be named after the system that uses them, but after the system that validates them. 🙈 

> _`CI` is at least a fill-in for Github Actions/GitLab-CI/BB pipelines and you know the provider its making calls to_

That's really contorted. The token is being used _from_ the continuous integration system, to authenticate _against_ the _forge_ API. 🙃 

> _I understand your insistence to use the term forge, but it is still not commonplace._

I don't mind if we use “forge” or not, but `CI` is by far less appropriate than `forge` in this context. That token is not [only/really] being used to authenticate to the `CI` API.

> _If the issue is handling the chance for a collision just silently keep `CML_TOKEN` then namespace `REPO_TOKEN` that's what users know already and will be easier (mentally) to move to._

Also arguably, `REPO_TOKEN` is an equally obtuse name: it's not scoped to a single repository, is not [only/mainly] used to access the [Git] repository, and “repo” is not a service you can authenticate against.

> _If we want to have naming holy wars, we should have handled this with the command renaming._

Too easy. Nobody will leave this thread alive. ⚔️ 

> _I'd argue for the moment there's no problem to fix so let's not make it one..._

Documentation, probably. Nothing is broken in the sense that it doesn't work, but...

**Comment by dacbd** [comment]
> > CI is at least a fill-in for Github Actions/GitLab-CI/BB pipelines and you know the provider its making calls to
>
> That's really contorted. The token is being used from the continuous integration system, to authenticate against the forge API. 🙃

A large portion of the token's usage is to register the CI Agent, and in terms of GitHub, the only case where a PAT is actually required. the `GITHUB_TOKEN` can be given appropriate permissions to perform all of the other actions.

> > If the issue is handling the chance for a collision just silently keep CML_TOKEN then namespace REPO_TOKEN that's what users know already and will be easier (mentally) to move to.
>
> Also arguably, REPO_TOKEN is an equally obtuse name: it's not scoped to a single repository, is not [only/mainly] used to access the [Git] repository, and “repo” is not a service you can authenticate against.

Being equally obtuse isn't a good enough reason to change it since its use is already established in documentation, blog posts, and [video] tutorials.

> > If we want to have naming holy wars, we should have handled this with the command renaming.
>
> Too easy. Nobody will leave this thread alive. ⚔️

😢 but true 🤺 

> > I'd argue for the moment there's no problem to fix so let's not make it one...
>
> Documentation, probably. Nothing is broken in the sense that it doesn't work, but...

Our Documentation is already behind in some updates, so I don't see the value in adding more to it.
It working, is the definition of not broken IMO. If we all agree to disagree on this point then maybe we can schedule the great CML re-write to python or maybe some rust

**Comment by 0x2b3bfa0** [comment]
> _A large portion of the token's usage is to register the CI Agent_

Yes, roughly 1 command out of 7. 🤨😉 

> _and in terms of GitHub, the only case where a PAT is actually required, the `GITHUB_TOKEN` can be given appropriate permissions to perform all of the other actions_

Tangential but true. Note that CML supports three different forges, and the token we're asking users to provide is being used for every operation, no matter which kind of token it is.

> _Being equally obtuse isn't a good enough reason to change it since its use is already established in documentation, blog posts, and [video] tutorials._

Almost agreed, in the sense that changing the documentation for such an insignificant detail is cumbersome. Still, that probably means that our documentation processes should be smoother; we'll always have to amend lots of bad API choices, and the earlier, the better. Sounds easier to fix 1 post and 4 videos now than 2 posts and 8 videos in six months. [^1]

> 😢 _but true_ 🤺

Don't forget your hauberk! 😄 

> _Our Documentation is already behind in some updates, so I don't see the value in adding more to it._

We can probably add it just as a reminder.[^2]

> _It working, is the definition of not broken IMO._

That's why we're fixing it. 😉 

> _If we all agree to disagree on this point then maybe we can schedule the great CML re-write to python or maybe some rust_

Absolutely [Wright](https://xkcd.com/106/). I was hoping for Brain... well, that language, but that's probably out of scope for this issue. Rust seems hard to justify, but Python would simplify quite a few integrations.

[^1]: [A healthy extreme programming paradign relies on frequent and smooth refactoring; if it's difficult, we should ask ourselves why](https://iterativeai.slack.com/archives/C0209RF6A5B/p1664302949923159?thread_ts=1664284116.737359&cid=C0209RF6A5B)
[^2]: [An issue tracker should be a priority list, rather than a checklist; “adding” is not the same operation as “prioritizing” in the sense that “not adding by fear of overwhelming” is harmful, but “not prioritizing” is just arguable at worst](https://iterativeai.slack.com/archives/C0209RF6A5B/p1661083143705089?thread_ts=1661056543.731139&cid=C0209RF6A5B)

**Comment by dacbd** [comment]
> Yes, roughly 1 command out of 7. 🤨😉

In proving my point I would dispute your interpretation of these numbers; you can say I'm cherry-picking, but looking at non-error invocations, it is closer 1/4. As well I would further discount `publish` usage as most cases there are multiple uses for a single `send-comment` making up what, a user and us by way of #1208, consider to be a single action. Additionally, 99% of the time `publish` uses a public API to function, not requiring any token.

**Comment by dacbd** [comment]
I would also like to state that `renaming !== refactoring`

**Comment by casperdcl** [comment]
Given we've agreed not to ever use the word "forge" in any context ever, `CML_GITHOST_TOKEN`?

I still think CI is fine because even GH doesn't really distinguish between "git provider" and "CI" (citation: https//api.github.com being used for both purposes)

**Comment by 0x2b3bfa0** [comment]
> _Given we've agreed not to ever use the word "forge" in any context ever<sup>[citation needed]</sup>_

Arguable as per comments linked from #1142 but, indeed, we can try not to use it.

> _`CML_GITHOST_TOKEN`_

I'm allergic to cache invalidation; worth visiting #1142 to find a generic name for GitHub/GitLab/Bitbucket if we really need one? 🤧

**Comment by 0x2b3bfa0** [comment]
> _I still think CI is fine because even GH doesn't really distinguish between "git provider" and "CI"_

Following that rule of thumb, we can use `CML_WIKI_TOKEN` or any other name related to a fraction of the functionality exposed by the forge API.

**Comment by 0x2b3bfa0** [comment]
I still haven't found alternatives (subjectively) better than `CML_TOKEN` because:

* It skillfully avoids naming forges as such, nor by any other name.
* Is already parsed by `yargs` as expected.

**Comment by casperdcl** [comment]
`CML_DRIVER_TOKEN`? :)

**Comment by 0x2b3bfa0** [comment]
> _`CML_DRIVER_TOKEN`_

This would reduce this problem to “just” #1142

**Comment by 0x2b3bfa0** [comment]
Opened #1272 as per https://github.com/iterative/cml/issues/763#issuecomment-1276700461
